import { ProvisioningState } from '../../../..'
import { VirtualCardEntity } from './virtualCardEntity'

/**
 * Provisional Card.
 *
 * @interface ProvisionalCard
 * @property {string} id Identifier generated by the Virtual Cards Service.
 * @property {Date} createdAt VirtualCards service timestamp to when the card entry was created.
 * @property {Date} updatedAt VirtualCards service timestamp to when the card entry was last updated.
 * @property {string} clientRefId Client Reference ID generated by the client.
 * @property {ProvisionalCardState} Current state of the cards status.
 * @property {VirtualCard | undefined} Fully fledged card.
 */
export interface ProvisionalVirtualCardEntity {
  id: string
  owner: string
  version: number
  createdAt: Date
  updatedAt: Date
  clientRefId: string
  provisioningState: ProvisioningState
  card: VirtualCardEntity | undefined
}
