import { Owner } from '@sudoplatform/sudo-common'
import { CardState } from '../../../..'
import { TransactionEntity } from '../transaction/transactionEntity'

/**
 * Domain representation of a virtual card entity.
 *
 * @interface VirtualCardEntity
 * @property {string} id Identifier generated by the Virtual Cards Service.
 * @property {OwnerEntity[]} owners List of identifiers of user/accounts associated with this card.
 * @property {string} owner Owner identifier of the card.
 * @property {number} version Virtual cards service supplied version.
 * @property {string} fundingSourceId Associative identifier of the funding source used to provision the card.
 * @property {VirtualCardStateEntity} state Current state of the cards status.
 * @property {string} cardHolder Owner of the card.
 * @property {string} alias User defined name associated with the card.
 * @property {string} last4 Last 4 digits on the card.
 * @property {string} pan Primary Account Number.
 * @property {string} csc Card Security Code.
 * @property {VirtualCardBillingAddressEntity | undefined} billingAddress Billing address associated with the card. If billing address is `nil`, the default billing address will be used.
 * @property {VirtualCardExpiryEntity} expiry Expiry of the card.
 * @property {string} currency Currency ISO code associated with the Card.
 * @property {Date} activeTo Date of the cards active to period.
 * @property {Date | undefined} cancelledAt Date that the card was cancelled at.
 * @property {Date} createdAt Date VirtualCards service timestamp to when the card entry was created.
 * @property {Date} updatedAt Date VirtualCards service timestamp to when the card entry was last updated.
 */
export interface VirtualCardEntity {
  id: string
  owners: Owner[]
  owner: string
  version: number
  createdAt: Date
  updatedAt: Date
  fundingSourceId: string
  currency: string
  state: CardState
  activeTo: Date
  cancelledAt?: Date | undefined
  last4: string
  cardHolder: string
  alias: string
  pan: string
  csc: string
  billingAddress?: VirtualCardBillingAddressEntity | undefined
  expiry: VirtualCardExpiryEntity
  lastTransaction?: TransactionEntity
}

/**
 * Domain representation of a Virtual Card Billing Address.
 *
 * @interface VirtualCardBillingAddressEntity
 * @property {string} addressLine1 First line of the address.
 * @property {string | undefined} addressLine2 Second line of the address.
 * @property {string} city City of the address.
 * @property {string} state State of the address.
 * @property {string} postalCode Postal code of the address.
 * @property {string} country Country of the address.
 */
export interface VirtualCardBillingAddressEntity {
  addressLine1: string
  addressLine2?: string
  city: string
  state: string
  postalCode: string
  country: string
}

/**
 * Domain representation of a Virtual Card Expiry.
 *
 * @interface VirtualCardExpiryEntity
 * @property {string} mm Month specifier, in format MM. e.g. (07 == July).
 * @property {string} yyyy Year specifier, in format YYYY. e.g. (2020 == Year 2020).
 */
export interface VirtualCardExpiryEntity {
  mm: string
  yyyy: string
}
