import {
  CachePolicy,
  DefaultLogger,
  NotSignedInError,
} from '@sudoplatform/sudo-common'
import { CreditCardNetwork, FundingSourceState } from '../../../..'
import { FundingSourceService } from '../../entities/fundingSource/fundingSourceService'
import { SudoUserService } from '../../entities/sudoUser/sudoUserService'

/**
 * Input for {@link ListFundingSourcesUseCase}.
 *
 * @interface ListFundingSourcesUseCaseInput
 * @property {CachePolicy} cachePolicy Cache policy determines the strategy for accessing the funding source records.
 * @property {number} limit Number of records to return. If omitted, the limit defaults to 10.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
interface ListFundingSourcesUseCaseInput {
  cachePolicy: CachePolicy
  limit?: number | undefined
  nextToken?: string | undefined
}

/**
 * Output for {@link ListFundingSourcesUseCase}.
 *
 * @interface ListFundingSourcesUseCaseOutput
 * @property {Array} fundingSources The list of funding sources retrieved in this use case.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
interface ListFundingSourcesUseCaseOutput {
  fundingSources: Array<{
    id: string
    owner: string
    version: number
    createdAt: Date
    updatedAt: Date
    state: FundingSourceState
    currency: string
    last4: string
    network: CreditCardNetwork
  }>
  nextToken?: string
}

/**
 * Application business logic for listing funding sources.
 */
export class ListFundingSourcesUseCase {
  private readonly log = new DefaultLogger(this.constructor.name)
  constructor(
    private readonly fundingSourceService: FundingSourceService,
    private readonly userService: SudoUserService,
  ) {}

  async execute({
    cachePolicy,
    limit,
    nextToken,
  }: ListFundingSourcesUseCaseInput): Promise<ListFundingSourcesUseCaseOutput> {
    this.log.debug(this.constructor.name, {
      cachePolicy,
      limit,
      nextToken,
    })
    if (!(await this.userService.isSignedIn())) {
      throw new NotSignedInError()
    }
    return await this.fundingSourceService.listFundingSources({
      cachePolicy,
      limit,
      nextToken,
    })
  }
}
